[project]
name = "stx-next-gen-memecoin"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/stx-next-gen-memecoin/stx-next-gen-memecoin/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stx-next-gen-memecoin]
path = "contracts/stx-next-gen-memecoin.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
